### ISSUE TITLE
Não exibir mensagens de usuário bloqueado

### ISSUE THREAD

**Issue by vcwild** [iaurg/42-transcendence#141]
## Descrição

Ao bloquear um usuário, não deve ser mais possível exibir mensagens do mesmo.

## TODO

- [x] Criar um ícone de bloqueio no tooltip de usuário
- [x] Ao clicar o botão, o usuário deve ser bloqueado
- [x] Não deve ser mais possível que você envie DMs ao usuário
- [x] Não poderá mais visualizar mensagens do usuário bloquado nos chats

**Comment by vcwild** [comment]
This is not complete @iaurg, please use Mentions instead of Closes for these cases.
